In [2]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:95% !important;}
div.cell.code_cell.rendered{width:95%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:22pt;}
.inner_cell{font-size:22pt;}
div.text_cell_render pre code {font-size:22pt; line-height:30px;}
div.output {font-size:20pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:22pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:20pt;padding:5px;}
table.dataframe{font-size:22px;}
</style>
"""))

# 1. 데이터 셋

In [4]:
import pandas as pd
url = 'https://raw.githubusercontent.com/4aix/data/refs/heads/master/ch13_apt_fillna_median.csv'
df = pd.read_csv(url)
df.sampleple()

     지역명   평당분양가격    연도   월
1817  경남  11863.5  2022  11

- 지역명2 : 지역명필드를 라벨인코딩하여 추가
- 독립변수(X) : 지역명2, 연도, 월
- 종속변수(y) : 평당분양가격
- 독립변수와 종속변수(2차원으로 reshape)의 스케일 조정

    * 정규화(MinMaxScaler) 작업후 : 지역명2m, 연도m, 월m 컬럼, 평당분양가격m => df_m
    * 표준화(StandardScaler) 작업후 : 지역명2s, 연도s,월s 컬럼, 평당분양가격s => df_s

    => 지역명, 연도, 월, 지역명2, 지역명2m, 연도m, 월m, 평당분양가격m, 지역명2s, 연도s, 월s, 평당분양가격s

y = w1*x1* = w2*x2 +w3*x3 +b

In [8]:
import numpy as np
from sklearn.preprocessing import LabelEncoder, MinMaxScaler, StandardScaler

# 2. 지역명의 라벨 인코딩

In [27]:
le = LabelEncoder()
df['지역명2'] = le.fit_transform(df['지역명'])
df.head(18)

,지역명,평당분양가격,연도,월,지역명2,지역명2m,연도m,월m,평당분양가격m,지역명2s,연도s,월s,평당분양가격s
0,서울,18189.0,2013,12,8,0.5000,0.000000,1.0,0.328198,0.000000,-1.875367,1.621960,1.168591
1,부산,8111.0,2013,12,7,0.4375,0.000000,1.0,0.065274,-0.204124,-1.875367,1.621960,-0.728312
2,대구,8080.0,2013,12,5,0.3125,0.000000,1.0,0.064466,-0.612372,-1.875367,1.621960,-0.734147
3,인천,10204.0,2013,12,11,0.6875,0.000000,1.0,0.119878,0.612372,-1.875367,1.621960,-0.334363
4,광주,6098.0,2013,12,4,0.2500,0.000000,1.0,0.012757,-0.816497,-1.875367,1.621960,-1.107203
5,대전,8321.0,2013,12,6,0.3750,0.000000,1.0,0.070753,-0.408248,-1.875367,1.621960,-0.688785
6,울산,8090.0,2013,12,10,0.6250,0.000000,1.0,0.064727,0.408248,-1.875367,1.621960,-0.732265
7,경기,10855.0,2013,12,1,0.0625,0.000000,1.0,0.136862,-1.428869,-1.875367,1.621960,-0.211830
8,세종,7601.0,2013,12,9,0.5625,0.000000,1.0,0.051969,0.204124,-1.875367,1.621960,-0.824305
9,강원,6230.0,2013,12,0,0.0000,0.000000,1.0,0.016201,-1.632993,-1.875367,1.621960,-1.082358
10,충북,6589.0,2013,12,16,1.0000,0.000000,1.0,0.025567,1.632993,-1.875367,1.621960,-1.014786
11,충남,6365.0,2013,12,15,0.9375,0.000000,1.0,0.019723,1.428869,-1.875367,1.621960,-1.056948
12,전북,6282.0,2013,12,13,0.8125,0.000000,1.0,0.017558,1.020621,-1.875367,1.621960,-1.072571
13,전남,5678.0,2013,12,12,0.7500,0.000000,1.0,0.001800,0.816497,-1.875367,1.621960,-1.186257
14,경북,6168.0,2013,12,3,0.1875,0.000000,1.0,0.014584,-1.020621,-1.875367,1.621960,-1.094028
15,경남,6473.0,2013,12,2,0.1250,0.000000,1.0,0.022541,-1.224745,-1.875367,1.621960,-1.036620
16,제주,7674.0,2013,12,14,0.8750,0.000000,1.0,0.053874,1.224745,-1.875367,1.621960,-0.810565
17,서울,17925.0,2014,1,8,0.5000,0.090909,0.0,0.321311,0.000000,-1.553588,-1.563144,1.118901

# 3. MinMaxScaling

In [17]:
X = df[['지역명2', '연도', '월']]
y = df[['평당분양가격']]
X.shape, y.shape

((2176, 3), (2176, 1))

In [19]:
scaler_x = MinMaxScaler()
df[['지역명2m', '연도m', '월m']] = scaler_x.fit_transform(X)

scaler_y = MinMaxScaler()
df['평당분양가격m'] = scaler_y.fit_transform(y)
df.head()

  지역명   평당분양가격    연도   월  지역명2   지역명2m  연도m   월m   평당분양가격m
0  서울  18189.0  2013  12     8  0.5000  0.0  1.0  0.328198
1  부산   8111.0  2013  12     7  0.4375  0.0  1.0  0.065274
2  대구   8080.0  2013  12     5  0.3125  0.0  1.0  0.064466
3  인천  10204.0  2013  12    11  0.6875  0.0  1.0  0.119878
4  광주   6098.0  2013  12     4  0.2500  0.0  1.0  0.012757

# 4. StandatdScaling

In [25]:
scaler_std_x = StandardScaler()
df[['지역명2s', '연도s', '월s']] = scaler_std_x.fit_transform(X)
scaler_std_y = StandardScaler()
y_data = df['평당분양가격'].values.reshape(-1,1)
df['평당분양가격s'] = scaler_std_y.fit_transform(y_data)
df.head()

,지역명,평당분양가격,연도,월,지역명2,지역명2m,연도m,월m,평당분양가격m,지역명2s,연도s,월s,평당분양가격s
0,서울,18189.0,2013,12,8,0.5000,0.0,1.0,0.328198,0.000000,-1.875367,1.62196,1.168591
1,부산,8111.0,2013,12,7,0.4375,0.0,1.0,0.065274,-0.204124,-1.875367,1.62196,-0.728312
2,대구,8080.0,2013,12,5,0.3125,0.0,1.0,0.064466,-0.612372,-1.875367,1.62196,-0.734147
3,인천,10204.0,2013,12,11,0.6875,0.0,1.0,0.119878,0.612372,-1.875367,1.62196,-0.334363
4,광주,6098.0,2013,12,4,0.2500,0.0,1.0,0.012757,-0.816497,-1.875367,1.62196,-1.107203

# 5. 지역명을 원핫인코딩

In [30]:
list(df.loc[:16].sort_values(by='지역명2')['지역명'])

['강원',
 '경기',
 '경남',
 '경북',
 '광주',
 '대구',
 '대전',
 '부산',
 '서울',
 '세종',
 '울산',
 '인천',
 '전남',
 '전북',
 '제주',
 '충남',
 '충북']

In [31]:
loc = list(df.loc[:16].sort_values(by='지역명2')['지역명'])
print('원핫인코딩 후 열이름 :', loc)

원핫인코딩 후 열이름 : ['강원', '경기', '경남', '경북', '광주', '대구', '대전', '부산', '서울', '세종', '울산', '인천', '전남', '전북', '제주', '충남', '충북']

In [32]:
from tensorflow.keras.utils import to_categorical
temp1 = to_categorical(df['지역명2'])
temp2 = pd.get_dummies(df['지역명2']).values
np.all(temp1==temp2)

True

In [33]:
# 원핫인코딩 방법1 : to_categorical
df[loc] = to_categorical(df['지역명2'])
df.head()

,지역명,평당분양가격,연도,월,지역명2,지역명2m,연도m,월m,평당분양가격m,지역명2s,...,부산,서울,세종,울산,인천,전남,전북,제주,충남,충북
0,서울,18189.0,2013,12,8,0.5000,0.0,1.0,0.328198,0.000000,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,부산,8111.0,2013,12,7,0.4375,0.0,1.0,0.065274,-0.204124,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,대구,8080.0,2013,12,5,0.3125,0.0,1.0,0.064466,-0.612372,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,인천,10204.0,2013,12,11,0.6875,0.0,1.0,0.119878,0.612372,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,광주,6098.0,2013,12,4,0.2500,0.0,1.0,0.012757,-0.816497,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [34]:
df.drop(loc, axis=1, inplace=True)

In [35]:
# 원핫인코딩 방법2 : get_dummies
df[loc] = pd.get_dummies(df['지역명2'])
df.head()

,지역명,평당분양가격,연도,월,지역명2,지역명2m,연도m,월m,평당분양가격m,지역명2s,...,부산,서울,세종,울산,인천,전남,전북,제주,충남,충북
0,서울,18189.0,2013,12,8,0.5000,0.0,1.0,0.328198,0.000000,...,0,1,0,0,0,0,0,0,0,0
1,부산,8111.0,2013,12,7,0.4375,0.0,1.0,0.065274,-0.204124,...,1,0,0,0,0,0,0,0,0,0
2,대구,8080.0,2013,12,5,0.3125,0.0,1.0,0.064466,-0.612372,...,0,0,0,0,0,0,0,0,0,0
3,인천,10204.0,2013,12,11,0.6875,0.0,1.0,0.119878,0.612372,...,0,0,0,0,1,0,0,0,0,0
4,광주,6098.0,2013,12,4,0.2500,0.0,1.0,0.012757,-0.816497,...,0,0,0,0,0,0,0,0,0,0

In [36]:
df.shape

(2176, 30)